#!/usr/bin/env python3
"""Interactive Cloudflare R2 credential wizard.

Walks the user through:
  1. Open Cloudflare dashboard to create / pick an R2 bucket
  2. Generate an Object Read & Write API token
  3. (Optional) bind a custom domain
  4. Paste the 4 values once
  5. Write to ~/.config/allincms-content-ops/r2.toml (gitignored at ~ level)
  6. Run a test upload to verify

Cloudflare won't let scripts create accounts / tokens — those 3 clicks
must happen in the dashboard. Everything after that is automated.

Privacy: `secret_access_key` is never printed back; `access_key_id` is
shown with middle redaction (xxx...xxx) in any output.
"""
import argparse
import getpass
import os
import sys
import tempfile
from pathlib import Path

CONFIG_DIR = Path.home() / ".config" / "allincms-content-ops"
CONFIG_FILE = CONFIG_DIR / "r2.toml"


def mask_key(s):
    if not s or len(s) < 10:
        return "***"
    return f"{s[:4]}...{s[-4:]}"


def prompt(label, default=None, secret=False):
    suffix = f" [{default}]" if default else ""
    if secret:
        v = getpass.getpass(f"{label}{suffix}: ")
    else:
        v = input(f"{label}{suffix}: ")
    return v.strip() or (default or "")


def write_config(account_id, bucket, access_key_id, secret_access_key, custom_domain):
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    body = f'''# Cloudflare R2 credentials for allincms-content-ops.
# Generated by r2_setup.py. Do NOT commit this file.
#
# Rotate the access key from https://dash.cloudflare.com/?to=/:account/r2/api-tokens
# if you suspect it's been exposed.

account_id = "{account_id}"
bucket = "{bucket}"
access_key_id = "{access_key_id}"
secret_access_key = "{secret_access_key}"
'''
    if custom_domain:
        body += f'custom_domain = "{custom_domain}"\n'
    CONFIG_FILE.write_text(body, encoding="utf-8")
    os.chmod(CONFIG_FILE, 0o600)  # owner-readable only


def read_config():
    if not CONFIG_FILE.is_file():
        return None
    out = {}
    for line in CONFIG_FILE.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" in line:
            k, v = line.split("=", 1)
            out[k.strip()] = v.strip().strip('"').strip("'")
    return out


def test_upload(config):
    """Round-trip a small file. Requires boto3."""
    try:
        import boto3
    except ImportError:
        print(
            "boto3 not installed — skipping live test. "
            "Install with: pip install boto3",
            file=sys.stderr,
        )
        return False
    endpoint = f"https://{config['account_id']}.r2.cloudflarestorage.com"
    client = boto3.client(
        "s3",
        endpoint_url=endpoint,
        aws_access_key_id=config["access_key_id"],
        aws_secret_access_key=config["secret_access_key"],
        region_name="auto",
    )
    test_key = "_allincms-r2-setup-test.txt"
    body = b"allincms-content-ops r2 setup test"
    try:
        client.put_object(Bucket=config["bucket"], Key=test_key, Body=body)
        got = client.get_object(Bucket=config["bucket"], Key=test_key)["Body"].read()
        # cleanup — never leave test artifacts
        client.delete_object(Bucket=config["bucket"], Key=test_key)
        return got == body
    except Exception as e:
        print(f"test upload failed: {e}", file=sys.stderr)
        return False


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--show", action="store_true", help="show current config (with key masking) and exit")
    parser.add_argument("--reset", action="store_true", help="delete existing config and rerun wizard")
    args = parser.parse_args()

    if args.show:
        cfg = read_config()
        if not cfg:
            print(f"No config at {CONFIG_FILE}")
            return 1
        print(f"# {CONFIG_FILE}")
        print(f"account_id      = {cfg.get('account_id', '')}")
        print(f"bucket          = {cfg.get('bucket', '')}")
        print(f"access_key_id   = {mask_key(cfg.get('access_key_id', ''))}")
        print(f"secret_access_key = ***(stored, not shown)***")
        if "custom_domain" in cfg:
            print(f"custom_domain   = {cfg['custom_domain']}")
        return 0

    if args.reset and CONFIG_FILE.is_file():
        CONFIG_FILE.unlink()
        print(f"removed {CONFIG_FILE}")

    if CONFIG_FILE.is_file() and not args.reset:
        print(f"config already exists at {CONFIG_FILE}")
        print("use --show to inspect, --reset to start over")
        return 1

    print()
    print("=== Cloudflare R2 setup wizard ===")
    print()
    print("Cloudflare needs you to do 3 things in the dashboard first.")
    print()
    print("STEP 1. Open: https://dash.cloudflare.com/?to=/:account/r2")
    print("        Sign in (free tier = 10 GB storage).")
    input("Press Enter when done.")
    print()
    print("STEP 2. Click 'Create bucket'. Give it a name (e.g. 'agently-media').")
    print("        Region: auto. Storage class: Standard.")
    bucket = prompt("Bucket name you chose")
    print()
    print("STEP 3. Go to R2 -> Manage R2 API Tokens -> Create API Token.")
    print("        Permission: 'Object Read & Write'. Scope: the bucket above.")
    print("        After creation, Cloudflare shows you 3 values once. Copy them:")
    print()
    account_id = prompt("Account ID (32 hex chars)")
    access_key_id = prompt("Access Key ID")
    secret_access_key = prompt("Secret Access Key", secret=True)
    print()
    print("STEP 4 (optional). Bind a custom domain (e.g. media.yoursite.com)")
    print("        in R2 -> Settings -> Custom Domains.")
    print("        Skip if you want to use r2.dev URLs for now.")
    custom_domain = prompt("Custom domain (blank to skip)")
    print()

    write_config(account_id, bucket, access_key_id, secret_access_key, custom_domain)
    print(f"凭证已写入 {CONFIG_FILE}")
    print("This file is owner-readable only (chmod 600).")
    print("It will not appear in any stdout, manifest, or audit report from now on.")
    print()

    print("Testing a round-trip upload (small file)...")
    cfg = read_config()
    if test_upload(cfg):
        print("✓ test upload succeeded. R2 is ready.")
        print()
        print("To upload images, run:")
        print(f"  python3 allincms-content-ops/scripts/r2_upload.py <dir-or-files>")
        return 0
    else:
        print("✗ test upload failed. Check the values you pasted, or rotate the")
        print("  token and re-run --reset.")
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
